#!/bin/sh
set -e -u

# Creates a small SD card image for the Gumstix Overo.
#
# In practice, the Pragmatux tools will auto-expand this image during
# first boot, to fill the MMC device containg it.  The image emitted
# by this tool is therefore kept as small as possible to facilitate
# low-bandwidth distribution.
#
# TODO: what if the developer doesn't want auto-expansion?
#
# For reference, this script creates a disk image similar to what you
# would get with the following commands:
#
#   sudo dd if=/dev/zero of=${DEFAULT_IMAGE} bs=1M count=${DEFAULT_SIZE}
#   sudo sfdisk --in-order --Linux --unit M ${DEFAULT_IMAGE} <<-__EOF__
#   1,48,0xE,*
#   ,,,-
#   __EOF__
#

DEFAULT_CONFIG=/usr/share/mkos-overo/default.mstrap
DEFAULT_DEVICE=device-overo
DEFAULT_IMAGE=ptux.img
DEFAULT_SIZE=1024M

USAGE="${0##./}"' [-C] [-c config] [package]
  Options:
    -C          print default config template to stdout and exit
    -c config   use file <config> as alternate config template
    -n image    use <image> as the output image filename

  Environment:
    The command line takes precedence over the environment.
    MKOS_CONFIG  - multistrap configuration
    MKOS_PACKAGE - root package
'

fatal () {
	echo "$@" >&2
	exit 1
}

fix_owner () {
	# If called under sudo, set ownership to sudo's caller
	test "${SUDO_UID-}" && chown ${SUDO_UID-}:${SUDO_GID} "$@"
}

while [ "$#" != 0 ]
do
	case "$1,${2-}" in
		-c,?*)
			CONFIG="$2"
			shift
			shift
			;;
		-C,*)
			cat ${MKOS_CONFIG:-$DEFAULT_CONFIG}
			exit
			;;
		-n,?*|--image-name,?*)
			IMAGE="$2"
			shift
			shift
			;;
		-h,*|--help,*)
			man ${0##*/}
			exit
			;;
		-*)
			fatal "$USAGE"
			;;
		*)
			if [ -z "${DEVICE:-}" ]; then
				DEVICE="$1"
				shift
			else
				fatal "$USAGE"
			fi
			;;
	esac
done

# TODO: unfortunately, we need real root for now.
# TODO: but soon, we'll be able to use guestfish...

test "$(id -u)" = "0" || fatal "must run as root"
: ${CONFIG:=${MKOS_CONFIG:-$DEFAULT_CONFIG}}
test -r $CONFIG || fatal cannot read $CONFIG
: ${DEVICE:=${MKOS_DEVICE:-$DEFAULT_DEVICE}}
: ${IMAGE:=${MKOS_IMAGE:-$DEFAULT_IMAGE}}
test ! -e $IMAGE || fatal "refusing to overwrite $IMAGE"

cleanup () {
	test -n "$TEMPMOUNT" && umount $TEMPMOUNT/boot >/dev/null || :
	test -n "$TEMPMOUNT" && umount $TEMPMOUNT >/dev/null || :
	kpartx -d $IMAGE >/dev/null || :
	rm -rf $TEMPCONFIG $TEMPMOUNT $IMAGE
}
trap "cleanup; exit" INT TERM EXIT

TEMPCONFIG=$(mktemp --tmpdir mkos-overo.mstrap.XXXXXXXX)
sed -e "s/{{device-package}}/$DEVICE/" $CONFIG >$TEMPCONFIG
TEMPMOUNT=$(mktemp -d --tmpdir mkos-overo.mount.XXXXXXXX)
truncate --size=$DEFAULT_SIZE $IMAGE
fix_owner $IMAGE
parted -s $IMAGE -- \
	mklabel msdos \
	mkpart primary 1 50 \
	mkpart primary 50 -1 \
	>/dev/null
TMP=$(kpartx -av $IMAGE | head -1 | awk '{print $3}')
NODE=/dev/mapper/${TMP%p*}
mkfs.vfat -n boot -F 16 ${NODE}p1 >/dev/null 2>&1
parted -s $IMAGE -- set 1 lba on >/dev/null
mkfs.ext4 ${NODE}p2 >/dev/null 2>&1 #TODO options?
mount ${NODE}p2 $TEMPMOUNT
mkdir $TEMPMOUNT/boot
mount ${NODE}p1 $TEMPMOUNT/boot

multistrap -f $TEMPCONFIG -d $TEMPMOUNT

# TODO: make this name follow $IMAGE
tar czf ptux.tgz -C $TEMPMOUNT .
fix_owner ptux.tgz

umount $TEMPMOUNT/boot
umount $TEMPMOUNT
kpartx -d $IMAGE >/dev/null
rm -r $TEMPMOUNT
rm $TEMPCONFIG

trap - INT TERM EXIT

